site_name: Pinferencia
repo_url: https://github.com/underneathall/pinferencia
repo_name: Pinferencia
edit_uri: blob/main/docs/
copyright: Copyright © 2020-2022 Jiuhe WANG underneathall.com, underneathall.app All Rights Reserved.
theme:
  name: material
  language: en
  custom_dir: docs/overrides
  features:
    - search.suggest
    - navigation.expand
    # - navigation.indexes
    - navigation.tracking
    - content.code.annotate
    - navigation.tabs
  palette:
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono
  # favicon: assets/favicon.png
  icon:
    # logo: material/horse
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/wjiuhe

extra_css:
    - 'underneathall/css/termynal.css'
    - 'underneathall/css/custom.css'
extra_javascript:
    - 'underneathall/js/termynal.js'
    - 'underneathall/js/custom.js'

plugins:
  - search
  - minify:
      minify_html: true
  - i18n:
      material_alternate: true
      default_language: en
      languages:
        en:
          name: English
          build: true
        re:
          name: Seriouly, Doc
          build: true
        zh:
          name: 中文
          build: true
        rc:
          name: 正襟危坐版
          build: true
      nav_translations:
        zh:
          Home: 首页
          Get Started: 快速上手
          Overview: 介绍
          Pinferencia is different?: Pinferencia有何不同?
          Install: 安装

          # beginner's tutorial
          Beginner's Tutorial: 常规指南
          Serve a JSON Model: 启动一个JSON模型
          Serve a Function: 启动一个函数
          Serve PyTorch MNIST Model: 启动PyTorch MNIST模型
          What's Next: 下一步

          # advanced tutorial
          Advanced Tutorial:  进阶指南
          Models: 模型
          Machine Learning Frameworks: 机器学习框架
          Example: 案例
          Register Models: 注册模型
          Handlers: Handlers
          REST API: REST API
          Dependencies: 依赖
          Bert: Bert
          GPT2 - Text Generation: GPT2 - 文本生成
          Image Classification: 图像识别
          Google T5 - Translation: Google T5 - 翻译
          Model?: 模型?
          Examples: 例子
          HuggingFace: HuggingFace
          NLP: 自然语言处理
          Vision: Vision
          Frontend: 前端页面
          Requirements: 使用条件
          Reference: 参考
        rc:
          Home: 首页
          Get Started: 快速上手
          Overview: 介绍
          Pinferencia is different?: Pinferencia有何不同?
          Install: 安装

          # beginner's tutorial
          Beginner's Tutorial: 常规指南
          Serve a JSON Model: 启动一个JSON模型
          Serve a Function: 启动一个函数
          Serve PyTorch MNIST Model: 启动PyTorch MNIST模型
          What's Next: 下一步

          # advanced tutorial
          Advanced Tutorial:  进阶指南
          Models: 模型
          Machine Learning Frameworks: 机器学习框架
          Example: 案例
          Register Models: 注册模型
          Handlers: Handlers
          REST API: REST API
          Dependencies: 依赖
          Bert: Bert
          GPT2 - Text Generation: GPT2 - 文本生成
          Image Classification: 图像识别
          Google T5 - Translation: Google T5 - 翻译
          Model?: 模型?
          Examples: 例子
          HuggingFace: HuggingFace
          NLP: 自然语言处理
          Vision: Vision
          Frontend: 前端页面
          Requirements: 使用条件
          Reference: 参考

markdown_extensions:
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Get Started:
    - Overview: overview/index.md
    - Pinferencia is different?: pinferencia-is-different/index.md
    - Install: install/index.md
  - Examples:
    - HuggingFace:
      - Dependencies: ml/huggingface/dependencies/index.md
      - NLP:
        - Bert: ml/huggingface/pipeline/nlp/bert/index.md
        - GPT2 - Text Generation: ml/huggingface/pipeline/nlp/text-generation/index.md
        - Google T5 - Translation: ml/huggingface/pipeline/nlp/translation/index.md
      - Vision:
        - Image Classification: ml/huggingface/pipeline/vision/index.md
  - Beginner's Tutorial:
    - Overview: get-started/home/index.md
    - Serve a JSON Model: get-started/serve-a-json-model/index.md
    - Serve a Function: get-started/serve-a-function/index.md
    - Serve PyTorch MNIST Model: get-started/pytorch-mnist/index.md
    - What's Next: get-started/other-models/index.md
  - Advanced Tutorial:
    - Models:
      - Overview: models/home/index.md
      - Machine Learning Frameworks: models/machine-learning/index.md
      - Register Models: models/register/index.md
    - Handlers: handlers/index.md
    - Frontend:
      - Requirements: frontend/requirements/index.md
    #   - Customize: frontend/custom/index.md
    #   - Default Task Type: frontend/task/index.md
    #   - Connect to Other Backends: frontend/other-backends/index.md
    # - Backend:
    #   - Customize: backend/custom/index.md
    #   - Generate Client: create-client/index.md
  - Reference:
    - REST API: restapi/index.md
    # - CLI Flags: cli/index.md
