[tool.poetry]
name = "pinferencia"
version = "0.1.0a4"
description = "Aims to be the Simplest Machine Learning Model Inference Server"
authors = ["William Wang <wjiuhe@gmail.com>"]
license = "Apache-2.0 License"

[tool.poetry.dependencies]
python = "^3.7"
fastapi = "^0.75.1"
numpy = "^1.22.3"
uvicorn = { version = "^0.17.6", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
pytest-cov = "^3.0.0"
requests = "^2.27.1"

[tool.poetry.extras]
uvicorn = ["uvicorn"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
