# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: E2E Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        poetry build
        mkdir -p /opt/workspace/tests
        cp -r tests/e2e_tests /opt/workspace/tests/
        cp -r pyproject.toml poetry.lock pytest.ini setup.cfg dist /opt/workspace/
        cd /opt/workspace
        poetry install
        poetry run pip install dist/*whl
        sudo apt-get install -y gcc
        poetry run pip install streamlit playwright
        poetry run playwright install
    - name: Test with pytest and playwright
      run: |
        cd /opt/workspace && echo $(pwd) && poetry run pytest -vvv tests/e2e_tests
