# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PyTorch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  mnist:

    runs-on: ubuntu-latest
    name: pytorch

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
    - name: Test MNIST
      run: |
        /bin/bash tests/extra/pytorch/mnist/test.sh
